import type { InitData, PRDisplayData, BranchWithPR } from './types.js';

const MOCK_BRANCHES: BranchWithPR[] = [
  {
    name: 'main',
    author: 'craigory',
    date: new Date(Date.now() - 3600_000).toISOString(),
    isRemote: false,
    isCurrent: true,
    relativeDate: '1h ago',
    pr: undefined,
  },
  {
    name: 'feat/pr-dashboard',
    author: 'craigory',
    date: new Date(Date.now() - 7200_000).toISOString(),
    isRemote: false,
    isCurrent: false,
    relativeDate: '2h ago',
    pr: { number: 42, title: 'Add PR dashboard', state: 'open', draft: false },
  },
  {
    name: 'fix/scroll-overflow',
    author: 'alice',
    date: new Date(Date.now() - 86400_000).toISOString(),
    isRemote: false,
    isCurrent: false,
    relativeDate: '1d ago',
    pr: { number: 38, title: 'Fix scroll overflow in list', state: 'open', draft: false },
  },
  {
    name: 'feat/worktree-support',
    author: 'bob',
    date: new Date(Date.now() - 172800_000).toISOString(),
    isRemote: false,
    isCurrent: false,
    relativeDate: '2d ago',
    pr: { number: 35, title: 'Add git worktree support', state: 'open', draft: true },
  },
  {
    name: 'refactor/cli-structure',
    author: 'craigory',
    date: new Date(Date.now() - 259200_000).toISOString(),
    isRemote: false,
    isCurrent: false,
    relativeDate: '3d ago',
    pr: undefined,
  },
  {
    name: 'origin/feat/remote-branch',
    author: 'charlie',
    date: new Date(Date.now() - 345600_000).toISOString(),
    isRemote: true,
    isCurrent: false,
    relativeDate: '4d ago',
    pr: { number: 31, title: 'Remote branch feature', state: 'open', draft: false },
  },
  {
    name: 'feat/editor-detection',
    author: 'alice',
    date: new Date(Date.now() - 432000_000).toISOString(),
    isRemote: false,
    isCurrent: false,
    relativeDate: '5d ago',
    pr: { number: 29, title: 'Auto-detect installed editors', state: 'open', draft: false },
  },
  {
    name: 'fix/github-token-resolution',
    author: 'bob',
    date: new Date(Date.now() - 604800_000).toISOString(),
    isRemote: false,
    isCurrent: false,
    relativeDate: '7d ago',
    pr: undefined,
  },
  {
    name: 'feat/cache-layer',
    author: 'craigory',
    date: new Date(Date.now() - 864000_000).toISOString(),
    isRemote: false,
    isCurrent: false,
    relativeDate: '10d ago',
    pr: { number: 24, title: 'Add caching layer for PR data', state: 'open', draft: false },
  },
  {
    name: 'origin/dependabot/bun-1.4',
    author: 'dependabot',
    date: new Date(Date.now() - 1209600_000).toISOString(),
    isRemote: true,
    isCurrent: false,
    relativeDate: '14d ago',
    pr: { number: 20, title: 'Bump bun to 1.4', state: 'open', draft: false },
  },
];

const MOCK_PRS: PRDisplayData[] = [
  {
    nodeId: 'PR_1', number: 142, title: 'Add Electrobun desktop UI integration',
    state: 'open', draft: false,
    repoOwner: 'git-switchboard', repoName: 'git-switchboard',
    repoId: 'git-switchboard/git-switchboard', forkRepoId: null,
    headRef: 'feat/electrobun-ui', updatedAt: new Date(Date.now() - 1800_000).toISOString(),
    url: 'https://github.com/git-switchboard/git-switchboard/pull/142',
    author: 'craigory', role: 'author',
    ciLabel: '12\u2713', ciColor: '#9ece6a',
    reviewLabel: '\u2713 Approved', reviewColor: '#9ece6a',
    mergeLabel: '', mergeColor: '#565f89',
  },
  {
    nodeId: 'PR_2', number: 138, title: 'Fix rate limit tracking for GraphQL API',
    state: 'open', draft: false,
    repoOwner: 'git-switchboard', repoName: 'git-switchboard',
    repoId: 'git-switchboard/git-switchboard', forkRepoId: null,
    headRef: 'fix/rate-limit', updatedAt: new Date(Date.now() - 7200_000).toISOString(),
    url: 'https://github.com/git-switchboard/git-switchboard/pull/138',
    author: 'alice', role: 'assigned',
    ciLabel: '10\u2713 2\u2717', ciColor: '#f7768e',
    reviewLabel: '\u2717 Changes req', reviewColor: '#f7768e',
    mergeLabel: '', mergeColor: '#565f89',
  },
  {
    nodeId: 'PR_3', number: 135, title: 'Implement chunked PR refresh with viewport prefetching',
    state: 'open', draft: false,
    repoOwner: 'git-switchboard', repoName: 'git-switchboard',
    repoId: 'git-switchboard/git-switchboard', forkRepoId: null,
    headRef: 'feat/chunked-refresh', updatedAt: new Date(Date.now() - 14400_000).toISOString(),
    url: 'https://github.com/git-switchboard/git-switchboard/pull/135',
    author: 'craigory', role: 'author',
    ciLabel: '8\u2713 1\u231B', ciColor: '#e0af68',
    reviewLabel: 'Needs review', reviewColor: '#565f89',
    mergeLabel: '', mergeColor: '#565f89',
  },
  {
    nodeId: 'PR_4', number: 130, title: 'Add multi-editor support with auto-detection',
    state: 'open', draft: true,
    repoOwner: 'git-switchboard', repoName: 'git-switchboard',
    repoId: 'git-switchboard/git-switchboard', forkRepoId: null,
    headRef: 'feat/multi-editor', updatedAt: new Date(Date.now() - 86400_000).toISOString(),
    url: 'https://github.com/git-switchboard/git-switchboard/pull/130',
    author: 'bob', role: 'assigned',
    ciLabel: '?', ciColor: '#565f89',
    reviewLabel: '\u2026', reviewColor: '#565f89',
    mergeLabel: '\u2717 Conflict', mergeColor: '#f7768e',
  },
  {
    nodeId: 'PR_5', number: 127, title: 'Migrate to Zustand for PR dashboard state',
    state: 'open', draft: false,
    repoOwner: 'git-switchboard', repoName: 'git-switchboard',
    repoId: 'git-switchboard/git-switchboard', forkRepoId: null,
    headRef: 'refactor/zustand', updatedAt: new Date(Date.now() - 172800_000).toISOString(),
    url: 'https://github.com/git-switchboard/git-switchboard/pull/127',
    author: 'craigory', role: 'both',
    ciLabel: '15\u2713', ciColor: '#9ece6a',
    reviewLabel: '\u2713 Approved', reviewColor: '#9ece6a',
    mergeLabel: '', mergeColor: '#565f89',
  },
  {
    nodeId: 'PR_6', number: 122, title: 'Add clipboard and notification support',
    state: 'open', draft: false,
    repoOwner: 'git-switchboard', repoName: 'git-switchboard',
    repoId: 'git-switchboard/git-switchboard', forkRepoId: null,
    headRef: 'feat/clipboard', updatedAt: new Date(Date.now() - 259200_000).toISOString(),
    url: 'https://github.com/git-switchboard/git-switchboard/pull/122',
    author: 'charlie', role: 'assigned',
    ciLabel: '6\u2713', ciColor: '#9ece6a',
    reviewLabel: '~ Re-review', reviewColor: '#e0af68',
    mergeLabel: '', mergeColor: '#565f89',
  },
  {
    nodeId: 'PR_7', number: 118, title: 'Improve keyboard navigation with vim-style bindings',
    state: 'open', draft: false,
    repoOwner: 'git-switchboard', repoName: 'docs',
    repoId: 'git-switchboard/docs', forkRepoId: null,
    headRef: 'feat/vim-keys', updatedAt: new Date(Date.now() - 345600_000).toISOString(),
    url: 'https://github.com/git-switchboard/docs/pull/118',
    author: 'alice', role: 'author',
    ciLabel: '3\u2713', ciColor: '#9ece6a',
    reviewLabel: 'Needs review', reviewColor: '#565f89',
    mergeLabel: '', mergeColor: '#565f89',
  },
  {
    nodeId: 'PR_8', number: 115, title: 'Add SSO token resolution fallback',
    state: 'open', draft: false,
    repoOwner: 'git-switchboard', repoName: 'git-switchboard',
    repoId: 'git-switchboard/git-switchboard', forkRepoId: null,
    headRef: 'fix/sso-token', updatedAt: new Date(Date.now() - 604800_000).toISOString(),
    url: 'https://github.com/git-switchboard/git-switchboard/pull/115',
    author: 'bob', role: 'author',
    ciLabel: '9\u2713', ciColor: '#9ece6a',
    reviewLabel: '\u2713 Approved', reviewColor: '#9ece6a',
    mergeLabel: '', mergeColor: '#565f89',
  },
];

/** Default view for demo / standalone mode (URL param ?view=branch-picker|pr-dashboard) */
export function getMockInitData(): InitData {
  const params = new URLSearchParams(window.location.search);
  const view = params.get('view');

  if (view === 'branch-picker') {
    return {
      view: 'branch-picker',
      branches: MOCK_BRANCHES,
      currentUser: 'craigory',
      showRemote: false,
    };
  }

  // Default to PR dashboard
  return {
    view: 'pr-dashboard',
    prs: MOCK_PRS,
    repoMode: null,
  };
}
